# Generated by Django 5.1.4 on 2025-04-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('icon', models.FileField(upload_to='category_icons/', verbose_name='Иконка')),
                ('image', models.ImageField(upload_to='category_image/', verbose_name='Фотография')),
                ('color', models.CharField(default='#4C4DDC', max_length=100, verbose_name='Цвет')),
                ('order', models.IntegerField(default=0, verbose_name='порядок')),
            ],
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('image', models.ImageField(default='default.jpg', upload_to='metro_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная')),
                ('image', models.ImageField(upload_to='category_images/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='порядок')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='metro.category', verbose_name='Родительская категория')),
            ],
        ),
    ]
